### ISSUE TITLE
notice about licensing

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-init#102]
`Apertium-init` quietly makes the software GPLv3-or-later.  It would probably be better if a notice were given, along the lines of:

> The directory you just created includes a GPLv3-or-later license.  If you would like to license it differently, please adjust or replace the COPYING file accordingly.  Please note that code included in the Apertium project should be GPLv2-or-later-compatible.

**Comment by TinoDidriksen** [comment]
Edited (GPLv3-or-later, GPLv2-or-later). And agreed.

**Comment by ftyers** [comment]
Shouldn't it be `COPYING` file?

**Comment by TinoDidriksen** [comment]
Right, it is `COPYING`. Edited.
