### ISSUE TITLE
feature: support for giella-pairs

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-init#14]

**Comment by jonorthwash** [comment]
And pairs with other prefixes, e.g. ling073-xyz.

**Comment by unhammer** [comment]
"giella-pairs" are e.g. "apertium-sme-sma", which depends on "giella-sme" and "giella-sma".

**Comment by jonorthwash** [comment]
Oh, yeah.  I'm looking for something else.  I'll file a new issue.

**Comment by unhammer** [comment]
dupe of #32
