### ISSUE TITLE
add goal for untrimmed debug modes?

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-init#17]
See https://sourceforge.net/p/apertium/tickets/88/#b3d3

For all _pairs_, we should add a debug target that includes the untrimmed analyser (easy), and debug modes that are like the regular ones, but use the untrimmed analyser (boring).

**Comment by mr-martian** [comment]
The debug target is now `make untrimmed` and the modes are `eng-cat` → `@eng-cat`.
