### ISSUE TITLE
Could this be changed to GPLv3+

### ISSUE THREAD

**Issue by ghost** [apertium/apertium-init#20]
Title says all.

**Comment by unhammer** [comment]
alright with me; @sushain97 ?

**Comment by sushain97** [comment]
Yep.

**Comment by jonorthwash** [comment]
Same.

**Comment by jonorthwash** [comment]
So it just needs to be done now?

**Comment by sushain97** [comment]
Sounds right to me. Looks like there are no real other contributors.

**Comment by sushain97** [comment]
https://github.com/apertium/apertium-init/commit/169f1758aad3ab5b1a54f007a427950fbbce0824

**Comment by jonorthwash** [comment]
Hmm, did we not need to change the LICENSE file?  Looks like it was GPLv3 from the beginning?
