### ISSUE TITLE
support for more features in hfst modules

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-init#23]
Add optional support to hfst modules for enabling spelling modules, an extra [twoc module for morphotactic constraints](http://wiki.apertium.org/wiki/Morphotactic_constraints_with_twol), and spellrelax.  Perhaps these should all be options at configure/autogen time, so that they can be enabled as needed after a module is started, but skeletons of the files they require should probably also be provided.

**Comment by jonorthwash** [comment]
@mr-martian, are spelling module support and spellrelax also available options currently?

**Comment by mr-martian** [comment]
I'm pretty sure spellrelax is (`--with-spellrelax`, I think), but I don't know what spelling module support is.
