### ISSUE TITLE
apertium-tagger needs -x sometimes

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-init#31]
apertium-init needs to check whether the .prob files are made with the perceptron algorithm, and add -x to apertium-tagger if so. Otherwise, bootstrapped pairs will gobble up all memory and segfault as tagger tries to load the .prob as HMM.

E.g. apertium-eng's eng.prob is perceptron.

**Comment by unhammer** [comment]
How does one check that? (and if it's possible programmatically, shouldn't apertium-tagger do it?)

**Comment by sushain97** [comment]
I think we just need a new CLI flag...

**Comment by IlnarSelimcan** [comment]
Using the -x option with a **non**-perceptron .prob file throws an exception right away:

```
apertium-eng$ echo "hello world" | apertium -d . eng-morph | apertium-tagger -g -x eng.hmm.prob
terminate called after throwing an instance of 'DeserialisationException'
  what():  can't deserialise 1 byte integer type: can't deserialise byte
Aborted
```

**Not** using the -x option with a perceptron .prob file leads to a segfault, just as mentioned.

```
apertium-eng$ echo "hello world" | apertium -d . eng-morph | apertium-tagger -g eng.prob
^C
```

Not too sure whether this is useful.

**Comment by IlnarSelimcan** [comment]
But I have seen a different kind of error too:

```
apertium-tur$ echo "Bir kitap okudum" | apertium -d . tur-morph  | apertium-tagger -g -x tur.prob 
apertium-tagger: Unimplemented opcode:  at global #0 address #0
Try 'apertium-tagger --help' for more information.
```

**Comment by flammie** [comment]
I just thought of this recurring problem, maybe we can start to solve this in a more low-tech way by just having different filename suffixes for different models and have humans deal with the selecting right options when needed?

**Comment by mr-martian** [comment]
The really low-tech way to solve this is to just default to adding `-x` if the language is `eng`, since I think that's currently the only language that uses perceptron.

**Comment by unhammer** [comment]
For init, that sounds like the best thing to do, since no one will have time to implement the Right solution while dealing with the overwhelming deluge of issues opened due to lack of -x in new pairs … only slightly exaggerating :)

**Comment by mr-martian** [comment]
Fixed in https://github.com/apertium/apertium/commit/5c5edd983890f128810ec8f8a17816389e3bb8fd
