### ISSUE TITLE
Support bootstrapping pairs where one side is from GT infra

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-init#32]
Giellatekno pairs require slightly different makefile stuffs.  

These pairs are both directions GT:

git@github.com:/apertium/apertium-sme-sma.git
git@github.com:/apertium/apertium-sme-smj.git
git@github.com:/apertium/apertium-sme-smn.git

These are one direction GT:

git@github.com:/apertium/apertium-sme-nob.git

**Comment by sushain97** [comment]
I think this is a dup of #14. Correct me if I'm wrong.

**Comment by unhammer** [comment]
yeah, though this issue was more informative :)
