### ISSUE TITLE
Ignore .prob on bilingual modules

### ISSUE THREAD

**Issue by xavivars** [apertium/apertium-init#42]
Prob files have to exist, but they are on the monolingual modules. They shouldn't be versioned on the bilingual ones.

Example:
* `apertium-cat` -> `apertium-cat.cat.prob` **added** to GIT
* `apertium-spa` -> `apertium-cat.spa.prob` **added** to GIT
* `apertium-spa-cat` -> `cat-spa.prob` and `spa-cat.prob` **ignored** in GIT

**Comment by sushain97** [comment]
(adding as a GCI task)

**Comment by theosalex** [comment]
> apertium-cat -> apertium-cat.cat.prob added to GIT
> apertium-spa -> apertium-cat.spa.prob added to GIT

Aren't these just cat.prob and spa.prob?

**Comment by Sheogorath2** [comment]
> apertium-cat -> apertium-cat.cat.prob added to GIT
> apertium-spa -> apertium-cat.spa.prob added to GIT

Aren't these files named cat.prob and spa.prob?

**Comment by sushain97** [comment]
Yeah, I believe that was just a typo.
