### ISSUE TITLE
¿<?xml for xml files?

### ISSUE THREAD

**Issue by flammie** [apertium/apertium-init#49]
Could all xml files start with:

    <?xml version='1.0' encoding='utf-8'?>

It seems to make vim happy to select xml mode in my system, currently it's a bit random which files have this.

**Comment by flammie** [comment]
Imagine there's a valid XML 1.0 declaration with utf-8 where github issues just removed it there -_-

**Comment by sushain97** [comment]
@flammie you have to indent with 4 spaces for it to catch code :) I fixed it for you.

**Comment by sushain97** [comment]
@flammie do you mind pointing out which ones don't have it? I want to make a beginner GCI task out of this but want to confirm that it isn't a wild goose chase :)

**Comment by sushain97** [comment]
Ooh, yeah, I think `lrx` needs it. `rlx` isn't XML AFAIK.

Thanks for checking.

**Comment by sushain97** [comment]
There's also some inconsistency that the task can request should be fixed.
