### ISSUE TITLE
Auto warn when TODOs not replaced on push

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-init#55]
cc @ftyers @jonorthwash

**Comment by unhammer** [comment]
as in, when stuff that the user should have filled in in readme's etc. isn't filled in? that'd be great :) git hook?

**Comment by sushain97** [comment]
ahh, I wasn't thinking git hook as much as when someone uses the push feature of the script itself.

motivation is GCI folks leaving TODOs in e.g. the README

git hook would also cover a normal push but my concern is I personally would very quickly get annoyed by it and delete it. thoughts?

**Comment by sushain97** [comment]
Yeah there's a `-p` flag that's somewhat under-documented that @jonorthwash added.

Okay, let's go with the git hook that disallows `TODO` but allows `TODO(...)` i.e. a person/issue number in the parens.
