### ISSUE TITLE
-pe should equal -p -e, not a long form

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-init#92]
E.g., https://github.com/apertium/apertium-init/blob/master/main.py#L224 has `parser.add_argument('-pe', '--push-existing-to-github', ...` which is just wrong. There's also `-a1` and others. These should all be `--` instead, or changed to an actual single symbol.

**Comment by mr-martian** [comment]
Looks like the main thing necessary for this to happen is to set ``allow_abbrev=False`` when creating the argument parser.

**Comment by TinoDidriksen** [comment]
https://docs.python.org/3/library/argparse.html#argumentparser-objects says `allow_abbrev=False` will disable `-pe == -p -e` in versions 3.5-3.7, but won't again from 3.8. Regardless, we want `allow_abbrev=True` because we do want combined short options to match several options. What we don't want is `-pe` to match long options, but that's what `--pe` is for.

**Comment by jonorthwash** [comment]
Help message still says:
```
To push your new local repository to incubator in the apertium organisation on GitHub:
	apertium-init.py -pe /data/apertium/git/languages/apertium-abc apertium-abc
```
